In [ ]:
{
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "provenance": [],
            "authorship_tag": "ABX9TyNgKY+8Q7yDJrJpRrD5Fuya",
            "include_colab_link": true
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {
                "id": "view-in-github",
                "colab_type": "text"
            },
            "source": [
                "<a href=\"https://colab.research.google.com/github/nadiaiftikhani/DataMining/blob/main/TugasPertemuan3/prepocessing.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 1,
            "metadata": {
                "id": "Nwnsn7sYb6MD"
            },
            "outputs": [],
            "source": [
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "import pandas as pd"
            ]
        },
        {
            "cell_type": "markdown",
            "source": [
                "Numpy merupakan library python digunakan untuk komputasi matriks. \n",
                "Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot.\n",
                "..."
            ],
            "metadata": {
                "id": "vsMkGWgOeQPy"
            }
        },
        {
            "cell_type": "code",
            "source": [
                "dataset = pd.read_csv('Data.csv')\n",
                "x = dataset.iloc[:, :-1].values\n",
                "y = dataset.iloc[:, -1].values"
            ],
            "metadata": {
                "id": "n1Sgskfae2Tg"
            },
            "execution_count": 2,
            "outputs": []
        },
        {
            "cell_type": "code",
            "source": [
                "print(x)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "XvxJUzpKf3cl",
                "outputId": "e86e419d-c425-4532-84b1-89747278443c"
            },
            "execution_count": 3,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "[['France' 44.0 72000.0]\n",
                        " ['Spain' 27.0 48000.0]\n",
                        " ['Germany' 30.0 54000.0]\n",
                        " ['Spain' 38.0 61000.0]\n",
                        " ['Germany' 40.0 nan]\n",
                        " ['France' 35.0 58000.0]\n",
                        " ['Spain' nan 52000.0]\n",
                        " ['France' 48.0 79000.0]\n",
                        " ['Germany' 50.0 83000.0]\n",
                        " ['France' 37.0 67000.0]]\n"
                    ]
                }
            ]
        },
        {
            "cell_type": "code",
            "source": [
                "print(y)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "aDow0UHPgUXS",
                "outputId": "9780ed0c-cd82-40a7-85a3-8811fe48a13d"
            },
            "execution_count": 4,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']\n"
                    ]
                }
            ]
        },
        {
            "cell_type": "code",
            "source": [
                "from sklearn.impute import SimpleImputer\n",
                "imputer = SimpleImputer(missing_values=np.nan, strategy='mean')\n",
                "imputer.fit(x[:, 1:3])\n",
                "x[:, 1:3] = imputer.transform(x[:, 1:3])"
            ],
            "metadata": {
                "id": "R81-TrhXgedJ"
            },
            "execution_count": 5,
            "outputs": []
        },
        {
            "cell_type": "code",
            "source": [
                "print(x)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "7UThThxshlFP",
                "outputId": "19e1d885-c18e-4d1f-9b74-bc3917d3283c"
            },
            "execution_count": 6,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "[['France' 44.0 72000.0]\n",
                        " ['Spain' 27.0 48000.0]\n",
                        " ['Germany' 30.0 54000.0]\n",
                        " ['Spain' 38.0 61000.0]\n",
                        " ['Germany' 40.0 63777.77777777778]\n",
                        " ['France' 35.0 58000.0]\n",
                        " ['Spain' 38.77777777777778 52000.0]\n",
                        " ['France' 48.0 79000.0]\n",
                        " ['Germany' 50.0 83000.0]\n",
                        " ['France' 37.0 67000.0]]\n"
                    ]
                }
            ]
        },
        {
            "cell_type": "code",
            "source": [
                "from sklearn.compose import ColumnTransformer\n",
                "from sklearn.preprocessing import OneHotEncoder\n",
                "ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')\n",
                "x = np.array(ct.fit_transform(x))"
            ],
            "metadata": {
                "id": "dDFmk2pZhwjJ"
            },
            "execution_count": 7,
            "outputs": []
        },
        {
            "cell_type": "code",
            "source": [
                "print(x)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "wbFZJY3Biudj",
                "outputId": "2753bf54-188f-4623-a784-cda6b0f39d9c"
            },
            "execution_count": 8,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "[[1.0 0.0 0.0 44.0 72000.0]\n",
                        " [0.0 0.0 1.0 27.0 48000.0]\n",
                        " [0.0 1.0 0.0 30.0 54000.0]\n",
                        " [0.0 0.0 1.0 38.0 61000.0]\n",
                        " [0.0 1.0 0.0 40.0 63777.77777777778]\n",
                        " [1.0 0.0 0.0 35.0 58000.0]\n",
                        " [0.0 0.0 1.0 38.77777777777778 52000.0]\n",
                        " [1.0 0.0 0.0 48.0 79000.0]\n",
                        " [0.0 1.0 0.0 50.0 83000.0]\n",
                        " [1.0 0.0 0.0 37.0 67000.0]]\n"
                    ]
                }
            ]
        },
        {
            "cell_type": "code",
            "source": [
                "from sklearn.preprocessing import LabelEncoder\n",
                "le = LabelEncoder()\n",
                "y = le.fit_transform(y)"
            ],
            "metadata": {
                "id": "QPAQ50LBi5rp"
            },
            "execution_count": 9,
            "outputs": []
        },
        {
            "cell_type": "code",
            "source": [
                "print(y)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "tbxr9L-7jHL5",
                "outputId": "a1b0de2f-f821-4608-8247-b51fc4475eab"
            },
            "execution_count": 10,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "[0 1 0 0 1 1 0 1 0 1]\n"
                    ]
                }
            ]
        },
        {
            "cell_type": "code",
            "source": [
                "from sklearn.model_selection import train_test_split\n",
                "x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)"
            ],
            "metadata": {
                "id": "m0rjby4HjVAd"
            },
            "execution_count": 11,
            "outputs": []
        },
        {
            "cell_type": "code",
            "source": [
                "print(x_train)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "Mosjq-gsj13u",
                "outputId": "55102211-cdc2-49d4-8606-0c7fe26bb008"
            },
            "execution_count": 12,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "[[0.0 0.0 1.0 38.77777777777778 52000.0]\n",
                        " [0.0 1.0 0.0 40.0 63777.77777777778]\n",
                        " [1.0 0.0 0.0 44.0 72000.0]\n",
                        " [0.0 0.0 1.0 38.0 61000.0]\n",
                        " [0.0 0.0 1.0 27.0 48000.0]\n",
                        " [1.0 0.0 0.0 48.0 79000.0]\n",
                        " [0.0 1.0 0.0 50.0 83000.0]\n",
                        " [1.0 0.0 0.0 35.0 58000.0]]\n"
                    ]
                }
            ]
        },
        {
            "cell_type": "code",
            "source": [
                "print(x_test)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "NUjzUBE-kBMp",
                "outputId": "04a974d2-2b9c-40ad-c3ae-3f5e3d828895"
            },
            "execution_count": 13,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "[[0.0 1.0 0.0 30.0 54000.0]\n",
                        " [1.0 0.0 0.0 37.0 67000.0]]\n"
                    ]
                }
            ]
        },
        {
            "cell_type": "code",
            "source": [
                "print(y_train)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "sJXIFFALkGjY",
                "outputId": "a8871210-311f-4e7f-c717-a348a7ae29df"
            },
            "execution_count": 14,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "[0 1 0 0 1 1 0 1]\n"
                    ]
                }
            ]
        },
        {
            "cell_type": "code",
            "source": [
                "print(y_test)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "yY9U1UIckMOH",
                "outputId": "50a78208-e2c7-48cb-b12c-d3d6004753b4"
            },
            "execution_count": 15,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "[0 1]\n"
                    ]
                }
            ]
        },
        {
            "cell_type": "code",
            "source": [
                "from sklearn.preprocessing import StandardScaler\n",
                "sc = StandardScaler()\n",
                "x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])\n",
                "x_test[:, 3:] = sc.transform(x_test[:, 3:])"
            ],
            "metadata": {
                "id": "wlQq9YxNliIU"
            },
            "execution_count": 17,
            "outputs": []
        },
        {
            "cell_type": "code",
            "source": [
                "print(x_train)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "_QMcvlvemR_6",
                "outputId": "55c1763f-4f97-4316-8f01-441dbec67fc0"
            },
            "execution_count": 18,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]\n",
                        " [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]\n",
                        " [1.0 0.0 0.0 0.566708506533324 0.633562432710455]\n",
                        " [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]\n",
                        " [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]\n",
                        " [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]\n",
                        " [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]\n",
                        " [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]\n"
                    ]
                }
            ]
        },
        {
            "cell_type": "code",
            "source": [
                "print(x_test)"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/"
                },
                "id": "A3JjYllQmX_y",
                "outputId": "8056ea68-7b84-4781-ca54-31534617f893"
            },
            "execution_count": 19,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]\n",
                        " [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]\n"
                    ]
                }
            ]
        }
    ]
}